//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examinator.QuizMethods {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuizMethods.QuizServiceSoap")]
    public interface QuizServiceSoap {
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTest", ReplyAction="*")]
        Examinator.QuizMethods.getTestResponse getTest(Examinator.QuizMethods.getTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTest", ReplyAction="*")]
        System.Threading.Tasks.Task<Examinator.QuizMethods.getTestResponse> getTestAsync(Examinator.QuizMethods.getTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTest", Namespace="http://tempuri.org/", Order=0)]
        public Examinator.QuizMethods.getTestRequestBody Body;
        
        public getTestRequest() {
        }
        
        public getTestRequest(Examinator.QuizMethods.getTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string difficulty;
        
        public getTestRequestBody() {
        }
        
        public getTestRequestBody(string category, string mode, string difficulty) {
            this.category = category;
            this.mode = mode;
            this.difficulty = difficulty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examinator.QuizMethods.getTestResponseBody Body;
        
        public getTestResponse() {
        }
        
        public getTestResponse(Examinator.QuizMethods.getTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTestResult;
        
        public getTestResponseBody() {
        }
        
        public getTestResponseBody(string getTestResult) {
            this.getTestResult = getTestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuizServiceSoapChannel : Examinator.QuizMethods.QuizServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuizServiceSoapClient : System.ServiceModel.ClientBase<Examinator.QuizMethods.QuizServiceSoap>, Examinator.QuizMethods.QuizServiceSoap {
        
        public QuizServiceSoapClient() {
        }
        
        public QuizServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuizServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuizServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuizServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examinator.QuizMethods.getTestResponse Examinator.QuizMethods.QuizServiceSoap.getTest(Examinator.QuizMethods.getTestRequest request) {
            return base.Channel.getTest(request);
        }
        
        public string getTest(string category, string mode, string difficulty) {
            Examinator.QuizMethods.getTestRequest inValue = new Examinator.QuizMethods.getTestRequest();
            inValue.Body = new Examinator.QuizMethods.getTestRequestBody();
            inValue.Body.category = category;
            inValue.Body.mode = mode;
            inValue.Body.difficulty = difficulty;
            Examinator.QuizMethods.getTestResponse retVal = ((Examinator.QuizMethods.QuizServiceSoap)(this)).getTest(inValue);
            return retVal.Body.getTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examinator.QuizMethods.getTestResponse> Examinator.QuizMethods.QuizServiceSoap.getTestAsync(Examinator.QuizMethods.getTestRequest request) {
            return base.Channel.getTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examinator.QuizMethods.getTestResponse> getTestAsync(string category, string mode, string difficulty) {
            Examinator.QuizMethods.getTestRequest inValue = new Examinator.QuizMethods.getTestRequest();
            inValue.Body = new Examinator.QuizMethods.getTestRequestBody();
            inValue.Body.category = category;
            inValue.Body.mode = mode;
            inValue.Body.difficulty = difficulty;
            return ((Examinator.QuizMethods.QuizServiceSoap)(this)).getTestAsync(inValue);
        }
    }
}
