//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examinator.PasswordSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PasswordSvc.PassordResetServiceSoap")]
    public interface PassordResetServiceSoap {
        
        // CODEGEN: Generating message contract since element name emailAddress from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/forgotPassword", ReplyAction="*")]
        Examinator.PasswordSvc.forgotPasswordResponse forgotPassword(Examinator.PasswordSvc.forgotPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/forgotPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Examinator.PasswordSvc.forgotPasswordResponse> forgotPasswordAsync(Examinator.PasswordSvc.forgotPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class forgotPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="forgotPassword", Namespace="http://tempuri.org/", Order=0)]
        public Examinator.PasswordSvc.forgotPasswordRequestBody Body;
        
        public forgotPasswordRequest() {
        }
        
        public forgotPasswordRequest(Examinator.PasswordSvc.forgotPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class forgotPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string emailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newPassword;
        
        public forgotPasswordRequestBody() {
        }
        
        public forgotPasswordRequestBody(string emailAddress, string newPassword) {
            this.emailAddress = emailAddress;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class forgotPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="forgotPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Examinator.PasswordSvc.forgotPasswordResponseBody Body;
        
        public forgotPasswordResponse() {
        }
        
        public forgotPasswordResponse(Examinator.PasswordSvc.forgotPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class forgotPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string forgotPasswordResult;
        
        public forgotPasswordResponseBody() {
        }
        
        public forgotPasswordResponseBody(string forgotPasswordResult) {
            this.forgotPasswordResult = forgotPasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PassordResetServiceSoapChannel : Examinator.PasswordSvc.PassordResetServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassordResetServiceSoapClient : System.ServiceModel.ClientBase<Examinator.PasswordSvc.PassordResetServiceSoap>, Examinator.PasswordSvc.PassordResetServiceSoap {
        
        public PassordResetServiceSoapClient() {
        }
        
        public PassordResetServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassordResetServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassordResetServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassordResetServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Examinator.PasswordSvc.forgotPasswordResponse Examinator.PasswordSvc.PassordResetServiceSoap.forgotPassword(Examinator.PasswordSvc.forgotPasswordRequest request) {
            return base.Channel.forgotPassword(request);
        }
        
        public string forgotPassword(string emailAddress, string newPassword) {
            Examinator.PasswordSvc.forgotPasswordRequest inValue = new Examinator.PasswordSvc.forgotPasswordRequest();
            inValue.Body = new Examinator.PasswordSvc.forgotPasswordRequestBody();
            inValue.Body.emailAddress = emailAddress;
            inValue.Body.newPassword = newPassword;
            Examinator.PasswordSvc.forgotPasswordResponse retVal = ((Examinator.PasswordSvc.PassordResetServiceSoap)(this)).forgotPassword(inValue);
            return retVal.Body.forgotPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Examinator.PasswordSvc.forgotPasswordResponse> Examinator.PasswordSvc.PassordResetServiceSoap.forgotPasswordAsync(Examinator.PasswordSvc.forgotPasswordRequest request) {
            return base.Channel.forgotPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Examinator.PasswordSvc.forgotPasswordResponse> forgotPasswordAsync(string emailAddress, string newPassword) {
            Examinator.PasswordSvc.forgotPasswordRequest inValue = new Examinator.PasswordSvc.forgotPasswordRequest();
            inValue.Body = new Examinator.PasswordSvc.forgotPasswordRequestBody();
            inValue.Body.emailAddress = emailAddress;
            inValue.Body.newPassword = newPassword;
            return ((Examinator.PasswordSvc.PassordResetServiceSoap)(this)).forgotPasswordAsync(inValue);
        }
    }
}
